###################################################################################
#                           RENAME FILE TO local.toml                             #
#                   Do not move this file to another directoy                     #
#                                                                                 #
#                              Â© Blacklusion 2020                                 #
###################################################################################

[general]
    # Define the length of the pause between rewards claims
    # Note: one claim will be performed immediately after the service is started
    claimIntervalMs = 87000000

    # Activate reward claiming for specified chains
    chains = ["wax-mainnet", "wax-testnet"]

[chains]
    [chains.wax-mainnet]
        apiUrl = "APIURL"
        producerName = "PRODUCERNAME"
        permissionName = "PERMISSIONNAME"
        isGbm = true
        privateKey = "PRIVATEKEY"

    [chains.wax-testnet]
        apiUrl = "https://testnet.wax.blacklusion.io"
        producerName = "blacklusionx"
        permissionName = "claimrewards"
        isGbm = false
        privateKey = "PRIVATEKEY"